version: '3.3'

services:
  traefik:
    image: traefik:v2.11
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=kkywalk2@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik:/letsencrypt
    networks:
      - web
    deploy:
      labels:
        - "traefik.enable=false"
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any

  owncloud:
    image: owncloud/server
    environment:
      - OWNCLOUD_DOMAIN=cnt2020.hopto.org
      - OWNCLOUD_ADMIN_USERNAME=kkywalk2
      - OWNCLOUD_ADMIN_PASSWORD=pruna333
      - OWNCLOUD_OVERWRITE_WEBROOT=/cloud
    volumes:
      - /root/my-services/owncloud:/mnt/data
    networks:
      - web
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.owncloud.rule=Host(`cnt2020.hopto.org`) && PathPrefix(`/cloud`)"
        - "traefik.http.routers.owncloud.entrypoints=websecure"
        - "traefik.http.routers.owncloud.tls.certresolver=myresolver"
        - "traefik.http.middlewares.owncloud-stripprefix.stripprefix.prefixes=/cloud"
        - "traefik.http.routers.owncloud.middlewares=owncloud-stripprefix"
        - "traefik.http.services.owncloud.loadbalancer.server.port=8080"
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure

volumes:
  traefik:

networks:
  web:
    external: true
